

TOP_CS_SCHOOLS = [
    "Carnegie Mellon University",
    "Massachusetts Institute of Technology",
    "Stanford University",
    "University of California - Berkeley",
    "University of Illinois - Urbana-Champaign",
    "Cornell University",
    "University of Washington",
    "Georgia Institute of Technology",
    "Princeton University",
    "University of Texas at Austin"
    "California Institute of Technology",
    "University of Michigan - Ann Arbor",
    "Columbia University",
    "University of California - Los Angeles",
    "University of Wisconsin - Madison",
    "Harvard University",
    "University of California - San Diego",
    "University of Maryland - College Park",
    "University of Pennsylvania",
    "Purdue University",
    "Rice University",
    "University of Massachusetts - Amherst",
    "University of Southern California",
    "Yale University",
    "Brown University",
    "Duke University",
    "Johns Hopkins University",
    "University of North Carolina - Chapel Hill",
    "University of Minnesota",
    "New York University",
    "Northwestern University",
    "Ohio State University",
    "Pennsylvania State University",
    "University of California - Irvine",
    "University of Chicago",
    "University of Virginia",
    "Rugters University",
    "University of California - Davis",
    "University of California - Santa Barbara",
    "Stony Brook University",
    "University of Colorado - Boulder",
    "Virginia Tech",
    "Arizona State University",
    "Dartmouth College",
    "North Carolina State University",
    "Texas A&M University",
    "University of Arizona",
    "University of Utah",
    "Boston University",
    "Northeastern University",
    "University of Florida",
    "University of Pittsburgh",
    "University of Rochester",
    "Washington University in St. Louis",
    "Indiana University - Bloomington",
    "Michigan State University",
    "Rensselaer Polytechnic Institute",
    "University of California - Santa Cruz",
    "University of Notre Dame",
    "Vanderbilt University"
]

MOST_ADMIRED_COMPANIES = [
    "Praetorian",
    "Apple",
    "Amazon",
    "Berkshire Hathaway",
    "Walt Disney",
    "Starbucks",
    "Microsoft",
    "Alphabet",
    "Netflix",
    "JPMorgan Chase"
    "National Security Agency",
    "Central Intelligence Agency",
    "Cigital",
    "Cisco",
    "Mandiant",
    "Duo Security",
    "Okta",
    "Google",
    "Salesforce",
    "Capital One"
]